repos:
-   repo: local
    hooks:
      - id: black
        name: format
        entry: make format-check
        language: system
        stages: [push]
        # pass_filenames: false
        # always_run: true
-   repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: make tests
        language: system
        stages: [push]
        pass_filenames: false
        always_run: true
